include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
